print("welcome to byjus the learning app")
print("this app clears all your doubts in science and maths and later history and civics")
name = input("username: ")
email = input("email:")
verify = input("input the verification code sent to email")
age = input("input yor age: ")
grade = input("input grade (number only)")
print("name: ")
print (name)
print("email")
print(email)
print("age: ")
print(age)
print("grade:")
